### ISSUE TITLE
【1/19 参加者情報をまとめました】「1/19(土) 14:00～21:00 256会」のお知らせ

### ISSUE THREAD

**Issue by jetlee0123** [jetlee0123/256times#1]
1/15 22:40 変更箇所
* 会場を新橋→「秋葉原」に変更しました。
* 開始時間を15時→「14時」に早めました。

1/17 12:32 追加
【重要：256会の交流を円滑にするためのお願い 】
下記のツールを使って得た画像(twitter風の名刺)を、ぼく宛(@YNanshin)にDMで送って頂くようお願いします(所要1分)。

ついった名刺
monokakitools.net/prof/

1/19 12:40 追記
【256会の参加メンバー情報を共有します】
https://www.dropbox.com/sh/5kqvsbigfcsd0uh/AABDfKFXvCk8a64GerniKr7ma?dl=0

・256回参加メンバーのtwitterプロフ画像をまとめました！

・プロフを見て「興味ある」「お話聞いてみたい」という人がいたら、会場で声をかけてみましょう。

※Dropboxアプリを入れてない方は「ウェブ版の利用を継続」をリンク先の画面で選んでください。

# 「256会」のお知らせ
***【参加者募集中！】256timesメンバーが集まってワイガヤするイベント
『256times飲み会＆お茶会 in秋葉原』を開催します。***

こんにちは。256timesメンバー(13daysで終了）の横田です。第0期生には選ばれませんでしたが、元旦から熱中するものがあったことは幸せでした。またチャレンジを通じて他のメンバーと交流することができたのも収穫です。せっかく頂いたご縁をそのまま終わらせるのはもったいない。そこで、ささやかな催しを企画させて頂きます。

# 「256会」の概要
1/19（土）14:00～21:00 秋葉原
 お昼の参加人数が増えた為、`開始時間を15時→***14時***に早めました`。
（お好きな時間帯にお越しください）

## 第1部 14:00～17:30 お茶会
予算：1000円（会場代のみです。飲み物やお菓子は各自ご用意ください）
場所：Weeyble コワーキングスペース秋葉原（秋葉原徒歩3分/「いきなりステーキ」の向かいのビル4F）
https://weeyble.com/access/
（仕事から遊びまで、自由にワイワイガヤガヤできるワーキングスペースです）

## 第2部 18:00～21:00 飲み会
予算：3500円(税込)  コース料理3時間飲み放題
場所：和民 / 秋葉原駅前店
https://tabelog.com/tokyo/A1310/A131001/13052086/

## 第3部 21:00～ 2次会（任意）
場所：秋葉原のどこか
※横田は終電までお付き合います。

# 「256会」の特徴
* だれでも（256time参加者なら、選考結果に関係なく）
* 低予算で（昼:1000円、夜:3500円)
* 好きな時間帯に参加できます（14:00～21:00)
* 秋葉原で開催します（よさげなコワーキングスペースがあるから）

# 「256会」はこういう人にオススメです。
* 256timesの目的「テクノロジーコミュニティで友達が作れるようになる」を地でいきたい人
* 元旦から一緒にがんばった256timesメンバーと美味い酒（orお茶）を呑みたい人
* 今までに関わったことがないタイプの人と交流したい人。

# 「256会」の参加メンバー（1/18 7:59 時点）
| No | ｱｶｳﾝﾄ名 | 第一部 | 第二部 | 備考| 
|---|---|---|---|---|
|0|@YNanshin|○|○|幹事の横田です！|
|1|@Hellomy432|○||14～飲み会前まで|
|2|@fktlnz|○|○||
|3|@Chikashilmakita|○|||
|4|@nekomical|○|||
|5|@kothiba|○|||
|6|@mjpurin|△|○|16時周辺に着予定|
|7|@comelounge|○|||
|8|@yuuta_sawamura|○|||
|9|@koheimiyamoto81|○|○||
|10|@nayokoNayoko|○|||
|11|@l_my_ds2|○|||
|12|@V_PG_N||○||
|13|yukoさん|○|||
|14|@_yzarc|○|||
|15|@e5843435|○|||
|16|@e_chai|○|○||
|17|@PythonSy4|○|||
|18|@piko0627pico|○|||
|19|@Hiroddin|○|||
|20|@udaemon|○|△||
|21|@shuhei_business||○||
|22|@murasak74594798|○|○||
|23|@anchor_cable|○|||
|24|@y_con|○|○||
|25|@kaiko5963|○|○||
|26|@kaisounomama|○|||
|27|@funpg||○||
|28|@Y_HAGIWARA|○|||
|29|@takkun_suzuki|○|||
|30|@rio_reach||○|18時過ぎるかも？|
|31|@isizawawataru||○||

# よくあるお問合せ
0.  どうして急に、新橋→「秋葉原」に変えたの？
・お昼の部の人数が想定よりも多かったからです（20名に迫る勢い）。
　お昼の会場メイン、新橋付近で探したところ秋葉原に落ち着きました。

1. 第二部は23時までだったんじゃないんですか？
・ワタミの都合です。
・「256times会」は21時まで、それ以降は任意参加です（僕は終電まで付き合います）。

2. 参加可否の連絡はいつまでにすればいいですか？
・目安は1/17(木) 12時までとさせてもらいます
   （なるはやが素敵です）

3. 体調が不安定なので、参加する"かも"でも、大丈夫ですか？
・昼の部は、ある程度は大丈夫です。
　夜の部は事前にお店を予約する関係で、できれば確定させてからお願いします。

4. お酒が飲めないんですが、第二部に参加しても大丈夫ですか？
・大丈夫です。ただし第二部は飲み放題の料金（35009円）なので、少し損した気分になります。

5. 256timesは早い段階で失格になりましたが、参加しても大丈夫ですか？
・大丈夫です。そこでマウントをかけてくる人はいないと思います（たぶん）。

6. 256times 0期生に選ばれた私ですが、参加しても大丈夫ですか？
・もちろんです。歓迎します。

7. 256timesに参加していないけど、「256times会」に参加してもいいですか？
・今回は初回につき、「256times参加者のみ」とさせていただきます。ご了承ください。

8. 今回都合が悪くて、「256times会」に参加できません。次回はありますか？
・19日の参加者の反応を見てですが、今後も256timesメンバーで継続的に集まりたくて、
　勉強会（もくもく会）とか実施したいなと個人的に思っています。

9. 直前になって、やっぱり参加したくなりました
・ルール違反ですが、人間そういうときもありますよね。ダメ元で連絡ください。

# 「256会」の問合せ先
Yokota Nanshin(@Ynanshin)
080-3573-8765

# おわり
以上です。
256timesメンバーの皆様と、新橋でワイガヤできるのを楽しみにしています。

**Comment by jetlee0123** [comment]
ssateteateata

**Comment by ponsu256** [comment]
Twitter名/ポンス（@Hellomy432）です。
私は15～飲み会前まで参加します。※確定です

**Comment by jetlee0123** [comment]
ポンスさん。承知しました。コメントありがとうございます。
> Twitter名/ポンス（@Hellomy432）です。
> 私は14～飲み会前まで参加します。※確定です

**Comment by fktlnz** [comment]
masa@fktlnzです。1部と2部参加できます。よろしくお願いします！

**Comment by jetlee0123** [comment]
> masa@fktlnzです。1部と2部参加できます。よろしくお願いします！

masaさん。コメントありがとうございます。承知しました！

**Comment by mitu-memo** [comment]
ともゆ@mitu_ykhm
取りまとめをありがとうございます。頼もしいですね(*^^*)
と言いながらすみません！欠席でお願いします。。。
みなさんで楽しんでくださいね。

**Comment by jetlee0123** [comment]
ともゆさん。
ありがとうございます。

いえいえお気になさらず。コメントいただけただけでも、うれしいです。

はい。みなで楽しんでまいります😃

**Comment by ymk25** [comment]
Twitter名:やしき(@nekomical)です。
256会の企画ありがとうございます(*^^*)
第1部のお茶会に参加させていただきます。
よろしくお願いします！

**Comment by kothiba** [comment]
Twitter名:コティーバ(@kothiba)です。
企画ありがとうございます。
第1部のお茶会のみになってしまいますが、参加させていただきます。
よろしくお願いします。

**Comment by mjpurin** [comment]
感動のお仕事ぶりです！ありがとうございます。
mjpurinは昼△夜○でお願いします。

**Comment by ghost** [comment]
かむ@comeloungeと申します。ご企画いただきありがとうございます。
ぜひ第1部のお茶会に参加させていただきたいです。何卒よろしくお願いいたします。

**Comment by yuta-sawamura** [comment]
こんにちは！澤村です。
一部、参加させてください^^
@yuuta_sawamura

**Comment by Toshiyuki-Takahashi** [comment]
こんにちは、高橋(@jyunia0110)です。
素敵な企画ありがとうございます！
当日の予定を確認しないとまだ参加可否が
分からないのですが先にコメントだけさせていただきました・・・！
（中途半端な状況でのコメントすいません・・・）

**Comment by koheimiyamoto81** [comment]
Kohei(@koheimiyamoto81)です。
1部、2部ともに参加させていただきます！
どうぞよろしくお願いします！

**Comment by naoko3in4** [comment]
こんにちは、なよ@nayokoNayokoです。
企画いただきありがとうございます！お茶会のみ参加させていただきます。
当日楽しみにしています！
よろしくお願いします

**Comment by mytn813** [comment]
こんにちは！Twitter名：美優（@l_my_ds2）です！
反応が遅れてしまい申し訳ないのですが、お昼のお茶会に顔を出せそうです！
よろしくお願いいたします。

**Comment by Fiddler25** [comment]
こんにちは
いてす（@V_PG_N ）です。
ご連絡遅くなり申し訳ないです。

2部から参加させてください。
それでは当日宜しくお願い致します！

**Comment by ghost** [comment]
こんにちは。
yukoです。twitterはやっておりませんが、256times参加者です。

一部のみ参加させて頂きたいです。
よろしくお願いいたします！

**Comment by shuhei-business** [comment]
ご調整ありがとうございます。
Twitter名shuheiです。

2部から参加させてください。
当日は宜しくお願い致します。

**Comment by soleil1986** [comment]
企画ありがとうございます。
昼の部参加でお願いします！
なまら北海道@Hiroddin
当日よろしくお願いします^ ^

**Comment by ycon7** [comment]
Twitter名:y_conです。
幹事いただきありがとうございます。
1部、2部ともに参加させてください。
よろしくお願いいたします。

**Comment by anchor-cable** [comment]
Twitter:anchor_cableです。
幹事ありがとうございますー。
1部のみ参加させてください。
よろしくおねがいします。

**Comment by chikashi-imakita** [comment]
こんばんは！素敵な企画ありがとうございます！
1部へ参加させてください。
Twitter：@ChikashiImakita
よろしくお願いいたします！

**Comment by kaiko5963** [comment]
こんばんは。
企画ありがとうございます！
1部・2部とも参加させてください！
よろしくお願いいたします。
Twitter：@kaiko5963

**Comment by jetlee0123** [comment]
幹事の横田です。
256timesメンバーーみなさま。出欠席のコメントを頂き、ありがとうございます。
1/15 23:15時点までに投稿いただいた内容(@kaiko5963さんまで)は、すべて本文に反映させて頂きました。

現時点の参加者が、
第1部が「19～22名」（検討中の方含む）
第2部が「9～11名」です。

・お昼の参加者が多く集まったため、箱の都合で場所を新橋→「秋葉原」に変更しました！
・お店の場所も確定しています。本文に記載済みですので、ご確認ください。
・「秋葉原だとちょっと」っていう方は、その旨をコメントください。

**Comment by YuYamashita** [comment]
多分参加できないと思って書き込まずにいたのですが、第一部の予定が空きましたっ
今からで大丈夫でしたら参加させてください^^
もし、難しければまた次回開催の時参加しますー
（twitter yuyuyuri/@kaisounomama)

**Comment by YuYamashita** [comment]
多分参加できないと思って書き込まずにいたのですが、第一部の予定が空きましたっ
今からの参加表明で申し訳ないのですが、よかったら参加させてください^^
もし、締め切っていて難しければまた次回開催の時参加しますー
（twitter yuyuyuri/@kaisounomama)

**Comment by Hase-python** [comment]
すいません、遅くなりました！第1部参加よろしくお願いします！
@PythonSy4

**Comment by jetlee0123** [comment]
@kaisounomamaさん
@PythonSy4さん

1部の参加、わかりました。

ありがとうございます。
もちろんバッチコイです😄

<参加人数>
1部=21〜24名
2部=9〜11名

**Comment by cashmere** [comment]
twitter @funpgです。

1部のみ参加させて下さい。
よろしくお願いします。

**Comment by yhagiwara24** [comment]
こんにちは！はぐ吉(@Y_HAGIWARA)です。
前外せない予定があると申し上げたのですが、予定の方がずれてくれたので1部に参加できるようになりました(o^^o)v
よろしくお願いします^ ^

**Comment by takkun-suzuki** [comment]
横田さん
企画と取りまとめ、ありがとうございます！
第一部に参加希望します。
よろしくお願いします。

twitter: @takkun_suzuki

**Comment by Toshiyuki-Takahashi** [comment]
> こんにちは、高橋(@jyunia0110)です。
> 素敵な企画ありがとうございます！
> 当日の予定を確認しないとまだ参加可否が
> 分からないのですが先にコメントだけさせていただきました・・・！
> （中途半端な状況でのコメントすいません・・・）

予定を確認したところ、今回は日程が合わずの為不参加とさせてください。。。
誠に残念ですが次の機会がありましたら参加させていただきたいです！

**Comment by jetlee0123** [comment]
takahashiさん。こんばんは。丁寧なコメントを頂きありがとうございます。お気持ち伝わりました。小規模でもいいので、何か企画できればと思います。話が具体化したらまたおしらせしますね。横田

**Comment by jetlee0123** [comment]
@funpgさん
@Y_HAGIWARAさん
@takkun_suzukiさん

コメント頂きありがとうございます。
諸々承知しました。お昼の部、人気ですねぇ〜😮

参加人数
1部=24〜27名
2部=9〜11名

**Comment by SaoriMatsuura** [comment]
こんにちは！Rio(@rio_reach)です。
取りまとめありがとうございます！！

2部に参加します。仕事のあとに行くのでちょっと18時すぎるかもしれません。
楽しみにしています！

**Comment by Tomoya1** [comment]
こんにちは筒井智也（@Isizawawataru）です。
企画・幹事ありがとうございます。:bow:
２部の方に参加できるようになりましたので参加させてもらいます。
連絡が遅くなりましたがよろしくお願いします。

**Comment by udagawamasaya** [comment]
宇田川（@udaemon123）です。
企画ありがとうございます！！
1部は参加で2部は△でお願いします^^

**Comment by jetlee0123** [comment]
【重要：256会の交流を円滑にするためのお願い 】

1/19(土) に参加される方々へ
下記のツールを使って得た画像(twitter風の名刺)を、ぼく宛(@YNanshin)にDMで送って頂くようお願いします(所要1分)。

ついった名刺
monokakitools.net/prof/

お手数ですが、ご協力お願いします

**Comment by interestor** [comment]
すみません、twitterで表明してOKかと勘違いをしていました。murasakiです、まだ間にあえばどちらも参加したいです。予約的に無理であれば一部だけで。よろしくおねがいします。

**Comment by jetlee0123** [comment]
@murasakiさん
両方とも参加で、わかりました。ちょうど今日申込むところでしたので、まだ大丈夫ですよ。

ありがとうございます。

<参加人数>
1部=25〜28名
2部=11〜14名

**Comment by kai4den** [comment]
おそくなりましたが昼の部で参加お願いします

**Comment by KFNO** [comment]
はじめまして。阿部(@kfno_)です。
明日急遽予定が空いたのですが参加受付はもう締め切られてますでしょうか？
もし可能でしたら昼の部参加させていただきたいです🙌

**Comment by jetlee0123** [comment]
阿部さん、まだ大丈夫ですよ。
お昼参加、了解しました。

twitterのプロフィール画像のご提出だけ、ご協力お願いします。

>【重要：256会の交流を円滑にするためのお願い 】
下記のツールを使って得た画像(twitter風の名刺)を、ぼく宛(@YNanshin)にDMで送って頂くようお願いします(所要1分)。

ついった名刺
monokakitools.net/prof/

**Comment by yukanosan** [comment]
大変遅れてしまいましたが、、
お昼の部に参加したいのですが、可能でしょうか？
よければ名刺をお送りします

**Comment by jetlee0123** [comment]
yukanosanこんばんは。

お昼の部でしたら大丈夫ですよ。
歓迎いたします。

名刺データよろしくお願いします

**Comment by koheimiyamoto81** [comment]
急なご連絡となってしまいすみません
用事が長引いてしまっているため15:00ごろより参加させていただきます

**Comment by jetlee0123** [comment]
【256会の参加メンバー情報を共有します】

https://www.dropbox.com/sh/5kqvsbigfcsd0uh/AABDfKFXvCk8a64GerniKr7ma?dl=0


・256回参加メンバーのtwitterプロフ画像をまとめました！

・プロフを見て「興味ある」「お話聞いてみたい」という人がいたら、会場で声をかけてみましょう。
  

※Dropboxアプリを入れてない方は「ウェブ版の利用を継続」をリンク先の画面で選んでください。

**Comment by jetlee0123** [comment]
koheimiyamotoさん、わかりました。
お昼の部は参加時間自由ですので、どうぞお気軽に。

※1回コメントにネガティブなスタンプを付けてしまいましたが、操作ミスです。失礼しました

**Comment by koheimiyamoto81** [comment]
かしこまりました！
そんなお気になさらないでください😁
ありがとうございます

**Comment by 5843435** [comment]
本日、昼の部のみ参加予定としておりましたが、家庭の都合で参加出来なくなってしまいました、すみません。
今回集まるメンバでSlack等グループ作られるようでしたら是非参加させていただきたいです。
また次回がありましたらそちらもぜひ参加したいです。よろしくお願いします。

**Comment by koheimiyamoto81** [comment]
本日は色々学ばせていただき、ありがとうございました！お気をつけてお帰りください
とても楽しかったです！

@kohei miyamoto81、こと宮本航平です
よろしければフォロー頂けると嬉しいです

本日はありがとうございました！

**Comment by jetlee0123** [comment]
新成人の@koheiさん
こちらこそ、今日はありがとうございました。若いエキスを頂き、感謝しています。

twitterアカウント、follow alreadyです。
koheiさんの前のめりな発信を期待しています。
